FROM node:22-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN apk add --no-cache libc6-compat

# Install dependencies based on pnpm-lock.yaml
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml* ./
RUN pnpm install

# Copy source code and configuration
COPY . .

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=development

EXPOSE 3000

CMD ["pnpm", "run", "dev"]
